### PR TITLE
Add more cvars, remove old broken stuff

### LINKED ISSUE #4: Add support for Ultiduo/Bball
Add automatic server configuration for Ultiduo and bball. Those are the only official formats not supported by TFTrue. Thank you and keep up the great work! :tada: :smile: :tada:

### LINKED ISSUE #10: Bunnyhopping plugin not working properly
You can bunnyhop but you have to fall off a height and then bhop. Just jumping off the floor pushes you back to the floor.

### PR DESCRIPTION
**Pull request by sapphonie**
Remove a lot of old broken cruft, added some new functionality, and cleaned up existing functionality:

- TFTrue's autoupdate feature will now only check once, at server start, after loading server cfgs (so people can disable it) with the new cvar, `tftrue_autoupdate` (#29)
- TFTrue now uses HTTP 2.0 to request files from http://whitelist.tf (still no HTTPS, sorry)
- TFTrue now respects whitelist.tf's cache length
- TFTrue will now no longer GET request a new whitelist from whitelist.tf and forcibly reload the current (same) whitelist uselessly when the values of `tftrue_whitelist_id` and other whitelist cvars remain the same after they are executed (#23)
- `tftrue_auto_bunnyhop` repeatedly and consistently crashes, despite having up to date signatures, so it has been removed ( indirectly closes #10 )
- `!speedmeter` has also been removed, as it was attatched to `tftrue_auto_bunnyhop`
- `tftrue_tournament_config` was removed, as it does not work with etf2l's 301 redirect to https, which TFTrue is unable to use (without an external lib and/or a bunch of rewriting) (indirectly closes #4 )
- Removed most "GetMap/GetGameType" code as it was related to `tftrue_tournament_config`
- Added error codes to better debug when `getaddrinfo` fails
- Add comments to otherwis magic number itemdef indexs
- Fix whitelist not reloading when changing `mp_tourament_whitelist` and not `tftrue_whitelist_id`
- Default  `tftrue_logs_roundend` to `1` to match the behavior of the logs.tf sourcemod plugin by F2
- Added `tftrue_enabled` (#21)
- Standardized spacing across the project, including removing hanging whitespace and converting spacing to smart tabs
- Cleaned up all bytesigs/symbol spacing and comments
- Updated `GetKillingWeaponName` Windows signature (#28)
- Added more verbose error messages on failing to load bytesigs/symbols etc
- Updated header files with new convars
- Changed fp:fast to fp:precise in compiler options
- Added mins and maxs to all cvars that needed them
- Upped tv_snapshotrate setting to 66, from 33
- Updated desc of `tftrue_restorestats`
- Added verbose and normal pause events (#17)- 
- Updated Readme

### CODE REVIEW

**Comment by sapphonie** [comment]
CLOSES:

#4 (config automation removed)
#10 (bunnyhopping removed)
#17 (added)
#21 (added)
#23
> TFTrue will now no longer GET request a new whitelist from whitelist.tf and forcibly reload the current (same) whitelist uselessly when the values of tftrue_whitelist_id and other whitelist cvars remain the same after they are executed

#28  (hopefully)
#29 (added `tftrue_autoupdate`)

**Comment by AnAkkk** [comment]
Hi, thanks for this. Could you please split different changes into different PRs, so that it is easier to review?
Also, a few things:
- Some people still use bunny hop so it would be better to fix it rather than remove it, I think it's just the offsets that are out of date
- All the custom HTTP code should really be removed, and replaced by ISteamHTTP (similarly to what I've done for the auto updater), so this would fix issues with tftrue_tournament_config and tftrue_whitelist_id.
- If adding a tftrue_enabled cvar (although I'm not sure it's really needed, you can disable what you want), it doesn't seem like unloading the plugin would be the right way to do it, as then you can't use the same cvar to reenable it.

**Comment by sapphonie** [comment]
> Some people still use bunny hop so it would be better to fix it rather than remove it, I think it's just the offsets that are out of date

The reason I removed it is that there's better sourcemod plugins/extensions/etc that add bunnyhopping, and I've never seen a server use it in several years (as it's always been pretty buggy or crash prone in my experience). To me it just seems like old code that nobody uses, (and I *really* do not want to track down the offset for linux, let alone windows). Similarly with `tftrue_tournament_config`, I've also never seen anyone utilize it, it's been broken since etf2 added a 301 https redirect god knows how long ago, *and* it has a lot of code checking the map type etc that I feel like can just be removed. Up to you though.

> If adding a tftrue_enabled cvar (although I'm not sure it's really needed, you can disable what you want), it doesn't seem like unloading the plugin would be the right way to do it, as then you can't use the same cvar to reenable it.

I should honestly just remove the cvar. The reason I opened that issue was that TFTrue was causing me crashing issues on my MvM server that I was running, and I have a git repo deploy it to all of my servers regardless of their type. This update should hopefully fix the crashing issues, nullifying my reason for having a cvar.

> Hi, thanks for this. Could you please split different changes into different PRs, so that it is easier to review?

LMK what you want split, and I can go ahead and do so w/ different branches.

**Comment by AnAkkk** [comment]
Let me think more about bunnyhop/tournament config.
Could you try to split most other things into separate PRs, like:
- Added mins and maxs to all cvars that needed them
- Upped tv_snapshotrate setting to 66, from 33
- Updated desc of tftrue_restorestats
- Added verbose and normal pause events
- TFTrue's autoupdate feature will now only check once, at server start, after loading server cfgs (so people can disable it) with the new cvar, tftrue_autoupdate
etc

**Pull request closed without merging**
