### PR TITLE
Replace Travis with GitHub Actions, add Windows build

### PR DESCRIPTION
**Pull request by Spaenny**
Implements #42, this includes an automatic build of windows in creation of a release tag. This will break AutoUpdater currently, because it does not push the binaries in the release folder of the repo anymore. The best option would be to rewrite AutoUpdater to work with GitHub Releases instead. 

Note: windows-2016 will be removed march 2022, I haven't been able to build TFTrue successfully under windows-2019. 
I just looked it up, this can be fixed via Chocolatey and https://stackoverflow.com/questions/33917454/cmake-how-to-specify-the-version-of-visual-c-to-work-with

### CODE REVIEW

**Comment by sapphonie** [comment]
Autoupdater should be wholly removed anyway, it's messy and annoying for users that use dockerized/git-based srcds hosting solutions

**Comment by Spaenny** [comment]
Nonetheless, I still haven't figured out why it's not compiling under VS2019. According to the README it should just compile fine; but it just doesn't.

**Comment by AnAkkk** [comment]
I guess the build instructions in the README just work on Linux, I build directly from Visual Studio 2019 on Windows. I will try to find out what are the correct parameters for cmake on Windows.

**Comment by Spaenny** [comment]
Hey, thanks for giving me an idea. VS 2019 seems to compile 64Bit by default. I added the flag -A Win32 to make it compile the 32Bit version. So there is no issue anymore with deprecated Windows Version anymore. 

Should I try to implement GitHub Actions to push the binaries to the repo or what exactly is the plan now?

**Comment by AnAkkk** [comment]
Thanks, and sorry for the delay, merged now with few changes to keep the AutoUpdater working.

**Pull request merged**
